ALTER TABLE books ALTER COLUMN id DROP DEFAULT;
ALTER TABLE books ALTER COLUMN id TYPE UUID USING gen_random_uuid();
ALTER TABLE books ALTER COLUMN id SET DEFAULT gen_random_uuid();
DROP SEQUENCE IF EXISTS books_id_seq;
