ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id TYPE UUID USING gen_random_uuid();
ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid();
DROP SEQUENCE IF EXISTS users_id_seq;

ALTER TABLE users
    ADD COLUMN full_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN user_type SMALLINT NOT NULL DEFAULT 3 CHECK (user_type IN (1, 2, 3)),
    ADD COLUMN concurrency_stamp TEXT NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN full_name DROP DEFAULT;
ALTER TABLE users ALTER COLUMN user_type DROP DEFAULT;
ALTER TABLE users ALTER COLUMN concurrency_stamp DROP DEFAULT;
